'use strict'

const gImgsSrcs =
    ['style/images/meme-imgs/meme-imgs (square)/1.jpg',
        'style/images/meme-imgs/meme-imgs (square)/2.jpg',
        'style/images/meme-imgs/meme-imgs (square)/3.jpg',
        'style/images/meme-imgs/meme-imgs (square)/4.jpg',
        'style/images/meme-imgs/meme-imgs (square)/5.jpg',
        'style/images/meme-imgs/meme-imgs (square)/6.jpg',
        'style/images/meme-imgs/meme-imgs (square)/7.jpg',
        'style/images/meme-imgs/meme-imgs (square)/8.jpg',
        'style/images/meme-imgs/meme-imgs (square)/9.jpg',
        'style/images/meme-imgs/meme-imgs (square)/10.jpg',
        'style/images/meme-imgs/meme-imgs (square)/11.jpg',
        'style/images/meme-imgs/meme-imgs (square)/12.jpg',
        'style/images/meme-imgs/meme-imgs (square)/13.jpg',
        'style/images/meme-imgs/meme-imgs (square)/14.jpg',
        'style/images/meme-imgs/meme-imgs (square)/15.jpg',
        'style/images/meme-imgs/meme-imgs (square)/16.jpg',
        'style/images/meme-imgs/meme-imgs (square)/17.jpg',
        'style/images/meme-imgs/meme-imgs (square)/18.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/2.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/003.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/004.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/005.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/5.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/006.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/8.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/9.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/12.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/19.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/Ancient-Aliens.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/drevil.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/img2.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/img4.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/img5.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/img6.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/img11.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/img12.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/leo.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/meme1.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/One-Does-Not-Simply.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/Oprah-You-Get-A.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/patrick.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/putin.jpg',
        'style/images/meme-imgs/meme-imgs (various aspect ratios)/X-Everywhere.jpg']